// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disclosure': string;
  'file': string;
  'openSummary': string;
  'preview': string;
  'profileList': string;
  'retained': string;
  'summary': string;
}
export const cssExports: CssExports;
export default cssExports;
